server:
  port: 8080
  session:
    timeout: 300
logging:
  level:
    tk.mybatis: TRACE
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
application:
  #版本
  version: 1.0.0
  #文件上传路径
  profile: D:/profile/
spring:
  profiles: prod
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: ENC(dIH/Ed4Cj5yeR9CGWisaktt8OX0x83XD)
    password: ENC(lPMwHr2e56l7bxGv9tGpyw==)
    port: 6379
  datasource:
    name: ENC(lPMwHr2e56l7bxGv9tGpyw==)
    url:  ENC(sQCey8Bqw5PRRDpU0a6pgO6VcWK5W6I8CaqDGQRJGKPq8wUP8YQZDZvk6SUklHJaxqEQJixMo7IrdIt6Kr7+SfYI5c4QGhwS654SX3Vn5bPc5TFmFqKdVapDg6zKuIvvKNjH4ykZyomLOoJKeDcfqHBxFA8RfoJA)
    username: ENC(43KfjD2VqwKx6D6mp0yNE4wvYBuegKQ8hbIXmuNGX9E=)
    password: ENC(22/E0XAjHytVXPAJkxdtzIdZCHfs0ZOsZj82SOe5bAIPAEjxIXBIAe6UuOfTThTaRNgn4LVLDP8=)
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat,wall,log4j     #druid监控配置
    　dbcp2:
      　　min-idle: 5         #数据库连接池的最小维持连接数
      　　initial-size: 5     #初始化提供的连接数
      　　max-total: 5          #最大的连接数
      　　max-wait-millis: 200        #等待连接获取的最大超时时间
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mail:
    host: ENC(4F3l8/Jt56+6twVSusqBFnjEf3RvoTWb)
    port: 25
    default-encoding: utf-8
    username: ENC(gkqEgeTiScsCX7WuqgxBehsQplgpUGZg)
    password: ENC(vl/fa7Ykv8LoO5+5LRftpfEFd67blhKLpt2MpaFA1Dc=)
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.daily.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
path:
  include:
    - /api/**
  exclude:
    - /api/user/login
    - /api/user/reg
    - /api/user/reg/get/code
    - /api/user/info
    - /api/select/**
    - /index.html
    - /