package com.daily.dao.auto;

import com.daily.pojo.CitiesCity;
import com.daily.pojo.CitiesCityExample;
import java.util.List;

public interface CitiesCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long cityCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_city
     *
     * @mbggenerated
     */
    int insert(CitiesCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_city
     *
     * @mbggenerated
     */
    int insertSelective(CitiesCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_city
     *
     * @mbggenerated
     */
    List<CitiesCity> selectByExample(CitiesCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_city
     *
     * @mbggenerated
     */
    CitiesCity selectByPrimaryKey(Long cityCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CitiesCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CitiesCity record);
}