package com.daily.dao.auto;

import com.daily.pojo.CtiesProvince;

public interface CtiesProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_province
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long citiesProvinceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_province
     *
     * @mbggenerated
     */
    int insert(CtiesProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_province
     *
     * @mbggenerated
     */
    int insertSelective(CtiesProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_province
     *
     * @mbggenerated
     */
    CtiesProvince selectByPrimaryKey(Long citiesProvinceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CtiesProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CtiesProvince record);
}