package com.daily.dao.auto;

import com.daily.pojo.DailyFiles;
import com.daily.pojo.DailyFilesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyFilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    int insert(DailyFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    int insertSelective(DailyFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    List<DailyFiles> selectByExample(DailyFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    DailyFiles selectByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DailyFiles record, @Param("example") DailyFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DailyFiles record, @Param("example") DailyFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DailyFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DailyFiles record);
}