package com.daily.dao.auto;

import com.daily.pojo.Diary;
import com.daily.pojo.DiaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int deleteByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int insert(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int insertSelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    List<Diary> selectByExampleWithBLOBs(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    List<Diary> selectByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    Diary selectByPrimaryKey(Long diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Diary record);
}