package com.daily.dao.auto;

import com.daily.pojo.Learn;
import com.daily.pojo.LearnExample;
import com.daily.pojo.LearnWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LearnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long learnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    int insert(LearnWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    int insertSelective(LearnWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    List<LearnWithBLOBs> selectByExampleWithBLOBs(LearnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    List<Learn> selectByExample(LearnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    LearnWithBLOBs selectByPrimaryKey(Long learnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LearnWithBLOBs record, @Param("example") LearnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") LearnWithBLOBs record, @Param("example") LearnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Learn record, @Param("example") LearnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LearnWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(LearnWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Learn record);
}