package com.daily.dao.auto;

import com.daily.pojo.TravelNote;
import com.daily.pojo.TravelNoteExample;
import com.daily.pojo.TravelNoteWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TravelNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long travelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    int insert(TravelNoteWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    int insertSelective(TravelNoteWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    List<TravelNoteWithBLOBs> selectByExampleWithBLOBs(TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    List<TravelNote> selectByExample(TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    TravelNoteWithBLOBs selectByPrimaryKey(Long travelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TravelNoteWithBLOBs record, @Param("example") TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TravelNoteWithBLOBs record, @Param("example") TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TravelNote record, @Param("example") TravelNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TravelNoteWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TravelNoteWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TravelNote record);
}