package com.daily.pojo;

import java.io.Serializable;
import java.util.Date;

public class CitiesCounty implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_county.county_code
     *
     * @mbggenerated
     */
    private Long countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_county.county_name
     *
     * @mbggenerated
     */
    private String countyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_county.county_level
     *
     * @mbggenerated
     */
    private String countyLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_county.city_code
     *
     * @mbggenerated
     */
    private Long cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_county.updated
     *
     * @mbggenerated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_county.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cities_county
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_county.county_code
     *
     * @return the value of cities_county.county_code
     *
     * @mbggenerated
     */
    public Long getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_county.county_code
     *
     * @param countyCode the value for cities_county.county_code
     *
     * @mbggenerated
     */
    public void setCountyCode(Long countyCode) {
        this.countyCode = countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_county.county_name
     *
     * @return the value of cities_county.county_name
     *
     * @mbggenerated
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_county.county_name
     *
     * @param countyName the value for cities_county.county_name
     *
     * @mbggenerated
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_county.county_level
     *
     * @return the value of cities_county.county_level
     *
     * @mbggenerated
     */
    public String getCountyLevel() {
        return countyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_county.county_level
     *
     * @param countyLevel the value for cities_county.county_level
     *
     * @mbggenerated
     */
    public void setCountyLevel(String countyLevel) {
        this.countyLevel = countyLevel == null ? null : countyLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_county.city_code
     *
     * @return the value of cities_county.city_code
     *
     * @mbggenerated
     */
    public Long getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_county.city_code
     *
     * @param cityCode the value for cities_county.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(Long cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_county.updated
     *
     * @return the value of cities_county.updated
     *
     * @mbggenerated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_county.updated
     *
     * @param updated the value for cities_county.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_county.created
     *
     * @return the value of cities_county.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_county.created
     *
     * @param created the value for cities_county.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}