package com.daily.pojo;

import java.io.Serializable;
import java.util.Date;

public class CitiesProvince implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_province.province_code
     *
     * @mbggenerated
     */
    private Long provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_province.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_province.province_level
     *
     * @mbggenerated
     */
    private String provinceLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_province.updated
     *
     * @mbggenerated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_province.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cities_province
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_province.province_code
     *
     * @return the value of cities_province.province_code
     *
     * @mbggenerated
     */
    public Long getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_province.province_code
     *
     * @param provinceCode the value for cities_province.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(Long provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_province.province_name
     *
     * @return the value of cities_province.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_province.province_name
     *
     * @param provinceName the value for cities_province.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_province.province_level
     *
     * @return the value of cities_province.province_level
     *
     * @mbggenerated
     */
    public String getProvinceLevel() {
        return provinceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_province.province_level
     *
     * @param provinceLevel the value for cities_province.province_level
     *
     * @mbggenerated
     */
    public void setProvinceLevel(String provinceLevel) {
        this.provinceLevel = provinceLevel == null ? null : provinceLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_province.updated
     *
     * @return the value of cities_province.updated
     *
     * @mbggenerated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_province.updated
     *
     * @param updated the value for cities_province.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_province.created
     *
     * @return the value of cities_province.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_province.created
     *
     * @param created the value for cities_province.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}