package com.daily.pojo;

import java.io.Serializable;
import java.util.Date;

public class CitiesCity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_city.city_code
     *
     * @mbggenerated
     */
    private Long cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_city.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_city.city_level
     *
     * @mbggenerated
     */
    private String cityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_city.province_code
     *
     * @mbggenerated
     */
    private Long provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_city.updated
     *
     * @mbggenerated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities_city.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cities_city
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_city.city_code
     *
     * @return the value of cities_city.city_code
     *
     * @mbggenerated
     */
    public Long getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_city.city_code
     *
     * @param cityCode the value for cities_city.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(Long cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_city.city_name
     *
     * @return the value of cities_city.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_city.city_name
     *
     * @param cityName the value for cities_city.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_city.city_level
     *
     * @return the value of cities_city.city_level
     *
     * @mbggenerated
     */
    public String getCityLevel() {
        return cityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_city.city_level
     *
     * @param cityLevel the value for cities_city.city_level
     *
     * @mbggenerated
     */
    public void setCityLevel(String cityLevel) {
        this.cityLevel = cityLevel == null ? null : cityLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_city.province_code
     *
     * @return the value of cities_city.province_code
     *
     * @mbggenerated
     */
    public Long getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_city.province_code
     *
     * @param provinceCode the value for cities_city.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(Long provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_city.updated
     *
     * @return the value of cities_city.updated
     *
     * @mbggenerated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_city.updated
     *
     * @param updated the value for cities_city.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities_city.created
     *
     * @return the value of cities_city.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities_city.created
     *
     * @param created the value for cities_city.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}