package com.daily.pojo;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbggenerated
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.article_id
     *
     * @mbggenerated
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.article_title
     *
     * @mbggenerated
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.relation_table
     *
     * @mbggenerated
     */
    private String relationTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parent_comment_id
     *
     * @mbggenerated
     */
    private Long parentCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parent_comment_user_id
     *
     * @mbggenerated
     */
    private Long parentCommentUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_comment_id
     *
     * @mbggenerated
     */
    private Long replyCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_comment_user_id
     *
     * @mbggenerated
     */
    private Long replyCommentUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_level
     *
     * @mbggenerated
     */
    private Integer commentLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.status_id
     *
     * @mbggenerated
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.praise_num
     *
     * @mbggenerated
     */
    private Integer praiseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.top_status
     *
     * @mbggenerated
     */
    private Byte topStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbggenerated
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_name
     *
     * @return the value of comment.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_name
     *
     * @param userName the value for comment.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.article_id
     *
     * @return the value of comment.article_id
     *
     * @mbggenerated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.article_id
     *
     * @param articleId the value for comment.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.article_title
     *
     * @return the value of comment.article_title
     *
     * @mbggenerated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.article_title
     *
     * @param articleTitle the value for comment.article_title
     *
     * @mbggenerated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.relation_table
     *
     * @return the value of comment.relation_table
     *
     * @mbggenerated
     */
    public String getRelationTable() {
        return relationTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.relation_table
     *
     * @param relationTable the value for comment.relation_table
     *
     * @mbggenerated
     */
    public void setRelationTable(String relationTable) {
        this.relationTable = relationTable == null ? null : relationTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parent_comment_id
     *
     * @return the value of comment.parent_comment_id
     *
     * @mbggenerated
     */
    public Long getParentCommentId() {
        return parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parent_comment_id
     *
     * @param parentCommentId the value for comment.parent_comment_id
     *
     * @mbggenerated
     */
    public void setParentCommentId(Long parentCommentId) {
        this.parentCommentId = parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parent_comment_user_id
     *
     * @return the value of comment.parent_comment_user_id
     *
     * @mbggenerated
     */
    public Long getParentCommentUserId() {
        return parentCommentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parent_comment_user_id
     *
     * @param parentCommentUserId the value for comment.parent_comment_user_id
     *
     * @mbggenerated
     */
    public void setParentCommentUserId(Long parentCommentUserId) {
        this.parentCommentUserId = parentCommentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply_comment_id
     *
     * @return the value of comment.reply_comment_id
     *
     * @mbggenerated
     */
    public Long getReplyCommentId() {
        return replyCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply_comment_id
     *
     * @param replyCommentId the value for comment.reply_comment_id
     *
     * @mbggenerated
     */
    public void setReplyCommentId(Long replyCommentId) {
        this.replyCommentId = replyCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply_comment_user_id
     *
     * @return the value of comment.reply_comment_user_id
     *
     * @mbggenerated
     */
    public Long getReplyCommentUserId() {
        return replyCommentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply_comment_user_id
     *
     * @param replyCommentUserId the value for comment.reply_comment_user_id
     *
     * @mbggenerated
     */
    public void setReplyCommentUserId(Long replyCommentUserId) {
        this.replyCommentUserId = replyCommentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_level
     *
     * @return the value of comment.comment_level
     *
     * @mbggenerated
     */
    public Integer getCommentLevel() {
        return commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_level
     *
     * @param commentLevel the value for comment.comment_level
     *
     * @mbggenerated
     */
    public void setCommentLevel(Integer commentLevel) {
        this.commentLevel = commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.status_id
     *
     * @return the value of comment.status_id
     *
     * @mbggenerated
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.status_id
     *
     * @param statusId the value for comment.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.praise_num
     *
     * @return the value of comment.praise_num
     *
     * @mbggenerated
     */
    public Integer getPraiseNum() {
        return praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.praise_num
     *
     * @param praiseNum the value for comment.praise_num
     *
     * @mbggenerated
     */
    public void setPraiseNum(Integer praiseNum) {
        this.praiseNum = praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.top_status
     *
     * @return the value of comment.top_status
     *
     * @mbggenerated
     */
    public Byte getTopStatus() {
        return topStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.top_status
     *
     * @param topStatus the value for comment.top_status
     *
     * @mbggenerated
     */
    public void setTopStatus(Byte topStatus) {
        this.topStatus = topStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}