package com.daily.pojo;

import java.io.Serializable;
import java.util.Date;

public class DailyFiles implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_files.file_id
     *
     * @mbggenerated
     */
    private Long fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_files.file_path
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_files.file_url
     *
     * @mbggenerated
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_files.file_size
     *
     * @mbggenerated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_files.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_files.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_files.updeted
     *
     * @mbggenerated
     */
    private Date updeted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table daily_files
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_files.file_id
     *
     * @return the value of daily_files.file_id
     *
     * @mbggenerated
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_files.file_id
     *
     * @param fileId the value for daily_files.file_id
     *
     * @mbggenerated
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_files.file_path
     *
     * @return the value of daily_files.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_files.file_path
     *
     * @param filePath the value for daily_files.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_files.file_url
     *
     * @return the value of daily_files.file_url
     *
     * @mbggenerated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_files.file_url
     *
     * @param fileUrl the value for daily_files.file_url
     *
     * @mbggenerated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_files.file_size
     *
     * @return the value of daily_files.file_size
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_files.file_size
     *
     * @param fileSize the value for daily_files.file_size
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_files.user_id
     *
     * @return the value of daily_files.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_files.user_id
     *
     * @param userId the value for daily_files.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_files.created
     *
     * @return the value of daily_files.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_files.created
     *
     * @param created the value for daily_files.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_files.updeted
     *
     * @return the value of daily_files.updeted
     *
     * @mbggenerated
     */
    public Date getUpdeted() {
        return updeted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_files.updeted
     *
     * @param updeted the value for daily_files.updeted
     *
     * @mbggenerated
     */
    public void setUpdeted(Date updeted) {
        this.updeted = updeted;
    }
}