package com.daily.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Diary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_id
     *
     * @mbggenerated
     */
    private Long diaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_context
     *
     * @mbggenerated
     */
    private String diaryContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.dialy_date
     *
     * @mbggenerated
     */
    private Date dialyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.mood_type
     *
     * @mbggenerated
     */
    private Integer moodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.mood
     *
     * @mbggenerated
     */
    private String mood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.temperature
     *
     * @mbggenerated
     */
    private BigDecimal temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.weather_type
     *
     * @mbggenerated
     */
    private Integer weatherType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.weather
     *
     * @mbggenerated
     */
    private String weather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.status_id
     *
     * @mbggenerated
     */
    private Short statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.updated
     *
     * @mbggenerated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_html
     *
     * @mbggenerated
     */
    private String diaryHtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diary
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_id
     *
     * @return the value of diary.diary_id
     *
     * @mbggenerated
     */
    public Long getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_id
     *
     * @param diaryId the value for diary.diary_id
     *
     * @mbggenerated
     */
    public void setDiaryId(Long diaryId) {
        this.diaryId = diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_context
     *
     * @return the value of diary.diary_context
     *
     * @mbggenerated
     */
    public String getDiaryContext() {
        return diaryContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_context
     *
     * @param diaryContext the value for diary.diary_context
     *
     * @mbggenerated
     */
    public void setDiaryContext(String diaryContext) {
        this.diaryContext = diaryContext == null ? null : diaryContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.dialy_date
     *
     * @return the value of diary.dialy_date
     *
     * @mbggenerated
     */
    public Date getDialyDate() {
        return dialyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.dialy_date
     *
     * @param dialyDate the value for diary.dialy_date
     *
     * @mbggenerated
     */
    public void setDialyDate(Date dialyDate) {
        this.dialyDate = dialyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.mood_type
     *
     * @return the value of diary.mood_type
     *
     * @mbggenerated
     */
    public Integer getMoodType() {
        return moodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.mood_type
     *
     * @param moodType the value for diary.mood_type
     *
     * @mbggenerated
     */
    public void setMoodType(Integer moodType) {
        this.moodType = moodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.mood
     *
     * @return the value of diary.mood
     *
     * @mbggenerated
     */
    public String getMood() {
        return mood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.mood
     *
     * @param mood the value for diary.mood
     *
     * @mbggenerated
     */
    public void setMood(String mood) {
        this.mood = mood == null ? null : mood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.temperature
     *
     * @return the value of diary.temperature
     *
     * @mbggenerated
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.temperature
     *
     * @param temperature the value for diary.temperature
     *
     * @mbggenerated
     */
    public void setTemperature(BigDecimal temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.weather_type
     *
     * @return the value of diary.weather_type
     *
     * @mbggenerated
     */
    public Integer getWeatherType() {
        return weatherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.weather_type
     *
     * @param weatherType the value for diary.weather_type
     *
     * @mbggenerated
     */
    public void setWeatherType(Integer weatherType) {
        this.weatherType = weatherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.weather
     *
     * @return the value of diary.weather
     *
     * @mbggenerated
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.weather
     *
     * @param weather the value for diary.weather
     *
     * @mbggenerated
     */
    public void setWeather(String weather) {
        this.weather = weather == null ? null : weather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.status_id
     *
     * @return the value of diary.status_id
     *
     * @mbggenerated
     */
    public Short getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.status_id
     *
     * @param statusId the value for diary.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(Short statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.user_id
     *
     * @return the value of diary.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.user_id
     *
     * @param userId the value for diary.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.created
     *
     * @return the value of diary.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.created
     *
     * @param created the value for diary.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.updated
     *
     * @return the value of diary.updated
     *
     * @mbggenerated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.updated
     *
     * @param updated the value for diary.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_html
     *
     * @return the value of diary.diary_html
     *
     * @mbggenerated
     */
    public String getDiaryHtml() {
        return diaryHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_html
     *
     * @param diaryHtml the value for diary.diary_html
     *
     * @mbggenerated
     */
    public void setDiaryHtml(String diaryHtml) {
        this.diaryHtml = diaryHtml == null ? null : diaryHtml.trim();
    }
}