package com.daily.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Event implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_id
     *
     * @mbggenerated
     */
    private Long eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.time_cost
     *
     * @mbggenerated
     */
    private BigDecimal timeCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.plan_time
     *
     * @mbggenerated
     */
    private Date planTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.remind
     *
     * @mbggenerated
     */
    private Boolean remind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.remind_time
     *
     * @mbggenerated
     */
    private Date remindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.status_id
     *
     * @mbggenerated
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.updated
     *
     * @mbggenerated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_context
     *
     * @mbggenerated
     */
    private String eventContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_id
     *
     * @return the value of event.event_id
     *
     * @mbggenerated
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_id
     *
     * @param eventId the value for event.event_id
     *
     * @mbggenerated
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.time_cost
     *
     * @return the value of event.time_cost
     *
     * @mbggenerated
     */
    public BigDecimal getTimeCost() {
        return timeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.time_cost
     *
     * @param timeCost the value for event.time_cost
     *
     * @mbggenerated
     */
    public void setTimeCost(BigDecimal timeCost) {
        this.timeCost = timeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.user_id
     *
     * @return the value of event.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.user_id
     *
     * @param userId the value for event.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.plan_time
     *
     * @return the value of event.plan_time
     *
     * @mbggenerated
     */
    public Date getPlanTime() {
        return planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.plan_time
     *
     * @param planTime the value for event.plan_time
     *
     * @mbggenerated
     */
    public void setPlanTime(Date planTime) {
        this.planTime = planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.remind
     *
     * @return the value of event.remind
     *
     * @mbggenerated
     */
    public Boolean getRemind() {
        return remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.remind
     *
     * @param remind the value for event.remind
     *
     * @mbggenerated
     */
    public void setRemind(Boolean remind) {
        this.remind = remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.remind_time
     *
     * @return the value of event.remind_time
     *
     * @mbggenerated
     */
    public Date getRemindTime() {
        return remindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.remind_time
     *
     * @param remindTime the value for event.remind_time
     *
     * @mbggenerated
     */
    public void setRemindTime(Date remindTime) {
        this.remindTime = remindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.deleted
     *
     * @return the value of event.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.deleted
     *
     * @param deleted the value for event.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.status_id
     *
     * @return the value of event.status_id
     *
     * @mbggenerated
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.status_id
     *
     * @param statusId the value for event.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.created
     *
     * @return the value of event.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.created
     *
     * @param created the value for event.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.updated
     *
     * @return the value of event.updated
     *
     * @mbggenerated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.updated
     *
     * @param updated the value for event.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_context
     *
     * @return the value of event.event_context
     *
     * @mbggenerated
     */
    public String getEventContext() {
        return eventContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_context
     *
     * @param eventContext the value for event.event_context
     *
     * @mbggenerated
     */
    public void setEventContext(String eventContext) {
        this.eventContext = eventContext == null ? null : eventContext.trim();
    }
}