package com.daily.pojo;

import java.io.Serializable;
import java.util.Date;

public class Label implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.label_id
     *
     * @mbggenerated
     */
    private Long labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.label_context
     *
     * @mbggenerated
     */
    private String labelContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.label_type
     *
     * @mbggenerated
     */
    private Integer labelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.relation_id
     *
     * @mbggenerated
     */
    private Long relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.relation_table
     *
     * @mbggenerated
     */
    private Integer relationTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table label
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.label_id
     *
     * @return the value of label.label_id
     *
     * @mbggenerated
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.label_id
     *
     * @param labelId the value for label.label_id
     *
     * @mbggenerated
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.label_context
     *
     * @return the value of label.label_context
     *
     * @mbggenerated
     */
    public String getLabelContext() {
        return labelContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.label_context
     *
     * @param labelContext the value for label.label_context
     *
     * @mbggenerated
     */
    public void setLabelContext(String labelContext) {
        this.labelContext = labelContext == null ? null : labelContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.label_type
     *
     * @return the value of label.label_type
     *
     * @mbggenerated
     */
    public Integer getLabelType() {
        return labelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.label_type
     *
     * @param labelType the value for label.label_type
     *
     * @mbggenerated
     */
    public void setLabelType(Integer labelType) {
        this.labelType = labelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.relation_id
     *
     * @return the value of label.relation_id
     *
     * @mbggenerated
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.relation_id
     *
     * @param relationId the value for label.relation_id
     *
     * @mbggenerated
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.relation_table
     *
     * @return the value of label.relation_table
     *
     * @mbggenerated
     */
    public Integer getRelationTable() {
        return relationTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.relation_table
     *
     * @param relationTable the value for label.relation_table
     *
     * @mbggenerated
     */
    public void setRelationTable(Integer relationTable) {
        this.relationTable = relationTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.user_id
     *
     * @return the value of label.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.user_id
     *
     * @param userId the value for label.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.created
     *
     * @return the value of label.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.created
     *
     * @param created the value for label.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}