package com.daily.pojo;

import java.io.Serializable;

public class LearnWithBLOBs extends Learn implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.learn_html
     *
     * @mbggenerated
     */
    private String learnHtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.learn_context
     *
     * @mbggenerated
     */
    private String learnContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table learn
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.learn_html
     *
     * @return the value of learn.learn_html
     *
     * @mbggenerated
     */
    public String getLearnHtml() {
        return learnHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.learn_html
     *
     * @param learnHtml the value for learn.learn_html
     *
     * @mbggenerated
     */
    public void setLearnHtml(String learnHtml) {
        this.learnHtml = learnHtml == null ? null : learnHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.learn_context
     *
     * @return the value of learn.learn_context
     *
     * @mbggenerated
     */
    public String getLearnContext() {
        return learnContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.learn_context
     *
     * @param learnContext the value for learn.learn_context
     *
     * @mbggenerated
     */
    public void setLearnContext(String learnContext) {
        this.learnContext = learnContext == null ? null : learnContext.trim();
    }
}