package com.daily.pojo;

import java.io.Serializable;
import java.util.Date;

public class Learn implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.learn_id
     *
     * @mbggenerated
     */
    private Long learnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.learn_title
     *
     * @mbggenerated
     */
    private String learnTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.dir
     *
     * @mbggenerated
     */
    private Integer dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.status_id
     *
     * @mbggenerated
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.updated
     *
     * @mbggenerated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table learn
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.learn_id
     *
     * @return the value of learn.learn_id
     *
     * @mbggenerated
     */
    public Long getLearnId() {
        return learnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.learn_id
     *
     * @param learnId the value for learn.learn_id
     *
     * @mbggenerated
     */
    public void setLearnId(Long learnId) {
        this.learnId = learnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.learn_title
     *
     * @return the value of learn.learn_title
     *
     * @mbggenerated
     */
    public String getLearnTitle() {
        return learnTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.learn_title
     *
     * @param learnTitle the value for learn.learn_title
     *
     * @mbggenerated
     */
    public void setLearnTitle(String learnTitle) {
        this.learnTitle = learnTitle == null ? null : learnTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.dir
     *
     * @return the value of learn.dir
     *
     * @mbggenerated
     */
    public Integer getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.dir
     *
     * @param dir the value for learn.dir
     *
     * @mbggenerated
     */
    public void setDir(Integer dir) {
        this.dir = dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.tag
     *
     * @return the value of learn.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.tag
     *
     * @param tag the value for learn.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.status_id
     *
     * @return the value of learn.status_id
     *
     * @mbggenerated
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.status_id
     *
     * @param statusId the value for learn.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.user_id
     *
     * @return the value of learn.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.user_id
     *
     * @param userId the value for learn.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.updated
     *
     * @return the value of learn.updated
     *
     * @mbggenerated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.updated
     *
     * @param updated the value for learn.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn.created
     *
     * @return the value of learn.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn.created
     *
     * @param created the value for learn.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}