package com.daily.pojo;

import java.io.Serializable;

public class SpringScheduledTask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_scheduled_task.cron_id
     *
     * @mbggenerated
     */
    private Integer cronId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_scheduled_task.cron_key
     *
     * @mbggenerated
     */
    private String cronKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_scheduled_task.cron_expression
     *
     * @mbggenerated
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_scheduled_task.task_explain
     *
     * @mbggenerated
     */
    private String taskExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_scheduled_task.status_id
     *
     * @mbggenerated
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spring_scheduled_task
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_scheduled_task.cron_id
     *
     * @return the value of spring_scheduled_task.cron_id
     *
     * @mbggenerated
     */
    public Integer getCronId() {
        return cronId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_scheduled_task.cron_id
     *
     * @param cronId the value for spring_scheduled_task.cron_id
     *
     * @mbggenerated
     */
    public void setCronId(Integer cronId) {
        this.cronId = cronId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_scheduled_task.cron_key
     *
     * @return the value of spring_scheduled_task.cron_key
     *
     * @mbggenerated
     */
    public String getCronKey() {
        return cronKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_scheduled_task.cron_key
     *
     * @param cronKey the value for spring_scheduled_task.cron_key
     *
     * @mbggenerated
     */
    public void setCronKey(String cronKey) {
        this.cronKey = cronKey == null ? null : cronKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_scheduled_task.cron_expression
     *
     * @return the value of spring_scheduled_task.cron_expression
     *
     * @mbggenerated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_scheduled_task.cron_expression
     *
     * @param cronExpression the value for spring_scheduled_task.cron_expression
     *
     * @mbggenerated
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_scheduled_task.task_explain
     *
     * @return the value of spring_scheduled_task.task_explain
     *
     * @mbggenerated
     */
    public String getTaskExplain() {
        return taskExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_scheduled_task.task_explain
     *
     * @param taskExplain the value for spring_scheduled_task.task_explain
     *
     * @mbggenerated
     */
    public void setTaskExplain(String taskExplain) {
        this.taskExplain = taskExplain == null ? null : taskExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_scheduled_task.status_id
     *
     * @return the value of spring_scheduled_task.status_id
     *
     * @mbggenerated
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_scheduled_task.status_id
     *
     * @param statusId the value for spring_scheduled_task.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
}