package com.daily.pojo;

import java.io.Serializable;

public class TravelNoteWithBLOBs extends TravelNote implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_note.travel_html
     *
     * @mbggenerated
     */
    private String travelHtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_note.travel_note
     *
     * @mbggenerated
     */
    private String travelNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travel_note
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_note.travel_html
     *
     * @return the value of travel_note.travel_html
     *
     * @mbggenerated
     */
    public String getTravelHtml() {
        return travelHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_note.travel_html
     *
     * @param travelHtml the value for travel_note.travel_html
     *
     * @mbggenerated
     */
    public void setTravelHtml(String travelHtml) {
        this.travelHtml = travelHtml == null ? null : travelHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_note.travel_note
     *
     * @return the value of travel_note.travel_note
     *
     * @mbggenerated
     */
    public String getTravelNote() {
        return travelNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_note.travel_note
     *
     * @param travelNote the value for travel_note.travel_note
     *
     * @mbggenerated
     */
    public void setTravelNote(String travelNote) {
        this.travelNote = travelNote == null ? null : travelNote.trim();
    }
}